#!/bin/bash
echo "🚀 Démarrage du Frontend Angular"
echo ""
echo "Structure créée avec succès !"
echo ""
echo "📋 Composants créés :"
echo "  ✅ Dashboard"
echo "  ✅ Teachers (Enseignants)"
echo "  ✅ Timetable (Emploi du temps)"
echo ""
echo "🔧 Services créés :"
echo "  ✅ API Service"
echo "  ✅ Teacher Service"
echo "  ✅ Timetable Service"
echo ""
echo "📱 Interface :"
echo "  ✅ Génération d'emploi du temps"
echo "  ✅ Visualisation par classe/enseignant"
echo "  ✅ Gestion des conflits"
echo ""
echo "Pour lancer le frontend :"
echo "1. npm install"
echo "2. ng serve"
echo "3. Ouvrir http://localhost:4200"
echo ""
echo "Backend API : http://localhost:3000"